# Generated by Django 5.0.6 on 2024-06-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='community_hall',
            fields=[
                ('community_hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('community_hall_name', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('locality', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1500)),
                ('contact_no', models.CharField(max_length=500)),
                ('capacity', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('manager_name', models.CharField(max_length=500)),
                ('community_hall_email_id', models.CharField(max_length=500)),
                ('cost', models.PositiveIntegerField()),
                ('img', models.ImageField(upload_to='Photos/')),
            ],
        ),
        migrations.CreateModel(
            name='garden',
            fields=[
                ('garden_id', models.AutoField(primary_key=True, serialize=False)),
                ('garden_name', models.CharField(max_length=1500)),
                ('city', models.CharField(max_length=500)),
                ('locality', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1500)),
                ('contact_no', models.CharField(max_length=500)),
                ('capacity', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('manager_name', models.CharField(max_length=500)),
                ('garden_email_id', models.CharField(max_length=500)),
                ('cost', models.PositiveIntegerField()),
                ('img', models.ImageField(upload_to='Photos/')),
            ],
        ),
        migrations.CreateModel(
            name='pool',
            fields=[
                ('pool_id', models.AutoField(primary_key=True, serialize=False)),
                ('pool_name', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('locality', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1500)),
                ('contact_no', models.CharField(max_length=500)),
                ('capacity', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('manager_name', models.CharField(max_length=500)),
                ('pool_email_id', models.CharField(max_length=500)),
                ('cost', models.PositiveIntegerField()),
                ('img', models.ImageField(upload_to='Photos/')),
            ],
        ),
    ]
