# Generated by Django 5.0.6 on 2024-06-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_community_hall_garden_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community_hall',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='garden',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hall',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pool',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
