# Generated by Django 5.0.6 on 2024-06-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_community_hall_capacity_alter_garden_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_hall',
            name='venue_type',
            field=models.CharField(default='Community Hall', max_length=100),
        ),
        migrations.AddField(
            model_name='garden',
            name='venue_type',
            field=models.CharField(default='Garden', max_length=100),
        ),
        migrations.AddField(
            model_name='hall',
            name='venue_type',
            field=models.CharField(default='Hall', max_length=100),
        ),
        migrations.AddField(
            model_name='pool',
            name='venue_type',
            field=models.CharField(default='Pool', max_length=100),
        ),
    ]
