# Generated by Django 5.0.6 on 2024-06-10 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_community_hall_capacity_alter_garden_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community_hall',
            name='venue_type',
            field=models.CharField(default='CommunityHall', max_length=100),
        ),
        migrations.AddField(
            model_name='garden',
            name='venue_type',
            field=models.CharField(default='Garden', max_length=100),
        ),
        migrations.AddField(
            model_name='hall',
            name='venue_type',
            field=models.CharField(default='Hall', max_length=100),
        ),
        migrations.AddField(
            model_name='pool',
            name='venue_type',
            field=models.CharField(default='Pool', max_length=100),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=500)),
                ('customer_name', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('booking_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]