# Generated by Django 5.0.6 on 2024-06-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_community_hall_venue_type_garden_venue_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='venue_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='addr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='custn',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='phn',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='vname',
            field=models.CharField(default='Venue', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
