# Generated by Django 5.0.6 on 2024-06-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_remove_booking_address_remove_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community_hall',
            name='venue_type',
            field=models.CharField(default='Community Hall', max_length=100),
        ),
    ]
